### ISSUE TITLE
Add a "Save as" option to just register the file on the smartphone

### ISSUE THREAD

**Issue by Valeryan24** [onyxbits/listmyaps#2] opened 2014-01-09 08:40 UTC
Hello,
When I began to use "List My Apps", I was surprised not to find how save the txt (or html if it is available in the future) directly on my smartphone (by opening the file explorer) because it was the first option I searched.
Then I saw the "Share" which opened a menu with a long list of applications (and some of them like APG, AnyMemo, Aard... not dedicated to file sharing), finally I tried with Dropbox and it worked very fine. The File Explorer was not on this list.
But I would like to also have an option to save the file on the phone (on intern memory or SD Card) and be able to copy it after when connecting the device on USB to my computer, or just open it on a text editor / browser on the smartphone.
Do you think it would be possible ?
Thanks !

**Comment by onyxbits** [comment] 2014-01-09 15:14
Am Donnerstag, den 09.01.2014, 00:40 -0800 schrieb Valeryan24:

> Hello,
> When I began to use "List My Apps", I was surprised not to find how
> save the txt (or html if it is available in the future) directly on my
> smartphone (by opening the file explorer) because it was the first
> option I searched.
> Then I saw the "Share" which opened a menu with a long list of
> applications (and some of them like APG, AnyMemo, Aard... not
> dedicated to file sharing), finally I tried with Dropbox and it worked
> very fine. The File Explorer was not on this list.
> But I would like to also have an option to save the file on the phone
> (on intern memory or SD Card) and be able to copy it after when
> connecting the device on USB to my computer, or just open it on a text
> editor / browser on the smartphone.
> Do you think it would be possible ?
> Thanks !
> 
> —
> Reply to this email directly or view it on GitHub.

It is possible, but it won't be implemented that way:
- I don't want LMA to request any permissions because I generally try to
  stick to "privacy by design" principles.
- "Save to file" is a "power user" feature. I am concerned with the
  average user who just wants a simple to use app that gets the job done.
  These users don't care about filemanagement. In fact they are usually
  not even tech savvy enough to understand filesystems and hence get
  easily confused by such features. In the best case that results in
  support mails (eating up my spare time), in the worst case the app gets
  deinstalled and poorly rated because it is too complex.
- I do plan an extension that will offer a "save to file" like
  functionality in the future.

**Comment by Valeryan24** [comment] 2014-01-09 17:20
OK, thanks for the answer, I understand.

I'l wait for the extension which will be important for me.

As I've a rooted smartphone, I try several Android distros like AOKP, CyanogenMod and often update them, especially during development stages. So LMA is a help to save all my app' list and reinstall them easily after a full wipe, that's why it is useful to keep the file on SD Card !

**Comment by onyxbits** [comment] 2014-01-09 17:43
Am Donnerstag, den 09.01.2014, 09:20 -0800 schrieb Valeryan24:

> OK, thanks for the answer, I understand.
> 
> I'l wait for the extension which will be important for me.
> 
> As I've a rooted smartphone, I try several Android distros like AOKP,
> CyanogenMod and often update them, especially during development
> stages. So LMA is a help to save all my app' list and reinstall them
> easily after a full wipe, that's why it is useful to keep the file on
> SD Card !

hm... ... makes you kinda wonder if there should be a "Save my list once
a day feature". Will have to think about it, but currently I'm rather
busy with Text Fiction, so this will take time.

As a workaround, I would suggest installing a simple text editor (e.g.
TED) and copy&pasting your list to it (copy&paste may actually be better
than share because of the buffer limit).

**Closed as completed** 2014-09-26 20:09 UTC

**Comment by anarcat** [comment] 2016-03-23 17:54
so i am doing the suggested workaround, but i think it's really clunky: it should be find for this app to write to the sdcard, or at least have some way of sharing the data directly.

**Comment by onyxbits** [comment] 2016-03-23 22:49
There definitely won't be a "save to file" feature. I neither want to implement half a filemanager nor deal with Users because Google decided to change the rules for accessing the SD card in Android 5.
